Insert bad tar ball and .md5 file detection

diff --git a/server/user/bitrot-detect b/server/user/bitrot-detect
--- a/server/user/bitrot-detect
+++ b/server/user/bitrot-detect
@@ -20,11 +20,27 @@ rm -f ${WORKDIR}/tbs.md5-*
 
 # We "find" all the controller directories and process them in alphabetical
 # order.
-find ${TARGETDIR}/ -maxdepth 1 -type d -printf '%P\n' | sort | while read ctrl; do
-    # For each controller, we read all the .md5 file contents re-emitting
-    # those contents with a file name that contains the full path.
-    cat ${TARGETDIR}/${ctrl}/*.md5 | while read hash file; do
-        echo "${hash} ${TARGETDIR}/${ctrl}/${file}"
+find ${TARGETDIR}/ -maxdepth 1 -mindepth 1 -type d -printf '%P\n' | sort | while read ctrl; do
+    find ${TARGETDIR}/${ctrl} -type f -name '*.tar.xz' | while read tb; do
+        # Detect empty tar balls
+        if [[ ! -s ${tb} ]]; then
+            printf -- "Empty tar ball found: %s\n" "${tb}" >&2
+        fi
+        _md5=${tb}.md5
+        # Detect missing .md5 files
+        if [[ ! -f ${_md5} ]]; then
+            printf -- "MD5 file for tar ball missing: %s\n" "${tb}" >&2
+        else
+            # Detect empty .md5 files
+            if [[ ! -s ${_md5} ]]; then
+                printf -- "Empty tar ball MD5 file found: %s\n" "${_md5}" >&2
+            else
+                # For each controller, we read all the .md5 file contents re-
+                # emitting those contents with a file name that contains the
+                # full path.
+                awk "{ print \$1, \"${TARGETDIR}/${ctrl}/\" \$2 }" ${_md5}
+            fi
+        fi
     done
     # All the output is captured into one file so that the requested
     # concurrency can be provided below.
