Refactor Tool Meister infra for data capture
The last set of `ssh` commands issued by the pbench-agent that are not
involved in orchestrating the Tool Meisters, outside of those issued by
the `bench-scripts`, are for `hostname -s` data collection on all
the registered remote tool hosts.

The Tool Meisters are now given the responsibility for collecting
information about their environment, including the version of the
pbench agent, and a more comprehensive collection of host name
information, returning that with their startup acknowledgement
payload.

This collected data set is now recorded by the Tool Data Sink, after
restructuring the action flow so that clients send action playloads to
the Tool Data Sink, which then forwards to the Tool Meisters.  This
gives the Tool Data Sink the ability to collect all the Tool Meister
information and write it to disk before acknowledging to the client
that startup is complete.

With this refactoring, we also collapse all the "sysinfo", "init", and
"end" actions into the respective `pbench-tool-meister-start` and
`pbench-tool-meister-stop` interfaces to simplify the CLI behaviors.

To make this possible, we add a new `Client` API used by the CLI
interfaces `pbench-tool-meister-start` and `pbench-tool-meister-stop`.

diff --git a/agent/util-scripts/test-bin/test-client-tool-meister b/agent/util-scripts/test-bin/test-client-tool-meister
--- a/agent/util-scripts/test-bin/test-client-tool-meister
+++ b/agent/util-scripts/test-bin/test-client-tool-meister
@@ -24,6 +24,8 @@ else
      group="${1}"
 fi
 
+sysinfo="block,security_mitigations,sos"
+
 function register {
     if [[ -z "${2}" ]]; then
         local remote_arg=""
@@ -61,31 +63,20 @@ function _timeout {
     timeout --kill-after=30 --signal TERM 60 $*
 }
 
-PBENCH_TM_BIND_HOSTNAME="localhost" _timeout pbench-tool-meister-start ${group}
+PBENCH_TM_BIND_HOSTNAME="localhost" _timeout pbench-tool-meister-start --sysinfo="${sysinfo}" "${group}"
 status=${?}
 if [[ ${status} -ne 0 ]]; then
-    printf -- "ERROR - \"pbench-tool-meister-start %s\" failed to execute successfully (exit code: %s)\n" "${group}" "${status}" >&2
-    exit 1
-fi
-
-_timeout pbench-collect-sysinfo --group="${group}" --dir="${benchmark_run_dir}" --sysinfo="block,security_mitigations,sos" beg
-status=${?}
-if [[ ${status} -ne 0 ]]; then
-    printf -- "ERROR - \"pbench-collect-sysinfo\" failed to execute successfully (exit code: %s)\n" "${status}" >&2
-    exit 1
-fi
-
-_timeout pbench-init-tools --group="${group}" --dir="${benchmark_run_dir}"
-status=${?}
-if [[ ${status} -ne 0 ]]; then
-    printf -- "ERROR - \"pbench-init-tools\" failed to execute successfully (exit code: %s)\n" "${status}" >&2
+    printf -- "ERROR - \"pbench-tool-meister-start --sysinfo='%s' '%s'\" failed to execute successfully (exit code: %s)\n" "${sysinfo}" "${group}" "${status}" >&2
     exit 1
 fi
 
 sample="sample42"
 iterations="0-iter-zero 1-iter-one"
 
+> ${benchmark_run_dir}/.iterations
+
 for iteration in ${iterations}; do
+    echo "${iteration}" >> ${benchmark_run_dir}/.iterations
     benchmark_results_dir="${benchmark_run_dir}/${iteration}/${sample}"
     mkdir -p ${benchmark_results_dir}
     status=${?}
@@ -127,23 +118,13 @@ if [[ "${3}" == "delayed-send" ]]; then
     done
 fi
 
-_timeout pbench-end-tools --group="${group}" --dir="${benchmark_run_dir}"
-status=${?}
-if [[ ${status} -ne 0 ]]; then
-    printf -- "ERROR - \"pbench-end-tools\" failed to execute successfully (exit code: %s)\n" "${status}" >&2
-    exit 1
+if [[ "${4}" == "interrupt" ]]; then
+    _timeout pbench-tool-meister-stop --sysinfo="${sysinfo}" --interrupt "${group}"
+else
+    _timeout pbench-tool-meister-stop --sysinfo="${sysinfo}" "${group}"
 fi
-
-_timeout pbench-collect-sysinfo --group="${group}" --dir="${benchmark_run_dir}" --sysinfo="block,security_mitigations,sos" end
 status=${?}
 if [[ ${status} -ne 0 ]]; then
-    printf -- "ERROR - \"pbench-collect-sysinfo\" failed to execute successfully (exit code: %s)\n" "${status}" >&2
-    exit 1
-fi
-
-_timeout pbench-tool-meister-stop
-status=${?}
-if [[ ${status} -ne 0 ]]; then
-    printf -- "ERROR - \"pbench-tool-meister-stop\" failed to execute successfully (exit code: %s)\n" "${status}" >&2
+    printf -- "ERROR - \"pbench-tool-meister-stop --sysinfo='%s' '%s'\" failed to execute successfully (exit code: %s)\n" "${sysinfo}" "${group}" "${status}" >&2
     exit 1
 fi
diff --git a/agent/util-scripts/test-bin/test-start-stop-tool-meister b/agent/util-scripts/test-bin/test-start-stop-tool-meister
--- a/agent/util-scripts/test-bin/test-start-stop-tool-meister
+++ b/agent/util-scripts/test-bin/test-start-stop-tool-meister
@@ -19,15 +19,22 @@ fi
 export _pbench_hostname
 
 if [[ -z "${1}" ]]; then
-     group="default"
+    group="default"
 else
-     group="${1}"
+    group="${1}"
 fi
 
 pbench-register-tool --group "${group}" --name mpstat
 status=${?}
 if [[ ${status} -ne 0 ]]; then
     printf -- "\"pbench-register-tool --group ${group} --name mpstat\" failed to execute successfully (exit code: ${status})\n" >&2
+    exit 1
+fi
+
+pbench-register-tool --group "${group}" --name perf -- '--record-opts="record -a -freq=100 -g --event=branch-misses --event=cache-misses --event=instructions"' '--report-opts="-I -g"'
+status=${?}
+if [[ ${status} -ne 0 ]]; then
+    printf -- "\"pbench-register-tool --group ${group} --name perf -- ...\" failed to execute successfully (exit code: ${status})\n" >&2
     exit 1
 fi
 
@@ -40,16 +47,28 @@ if [[ ${status} -ne 0 ]]; then
     exit 1
 fi
 
-_PBENCH_TOOL_DATA_SINK_LOG_LEVEL="info" _PBENCH_TOOL_MEISTER_START_LOG_LEVEL="debug" PBENCH_TM_BIND_HOSTNAME="localhost" pbench-tool-meister-start ${group}
+redis_pid_file="${benchmark_run_dir}/tm/redis_17001.pid"
+
+_PBENCH_TOOL_MEISTER_LOG_LEVEL="debug" _PBENCH_TOOL_DATA_SINK_LOG_LEVEL="debug" _PBENCH_TOOL_MEISTER_START_LOG_LEVEL="debug" PBENCH_TM_BIND_HOSTNAME="localhost" pbench-tool-meister-start --sysinfo="none" ${group}
 status=${?}
 if [[ ${status} -ne 0 ]]; then
     printf -- "\"pbench-tool-meister-start ${group}\" failed to execute successfully (exit code: ${status})\n" >&2
+    redis_pid="$(cat ${redis_pid_file} 2> /dev/null)"
+    if [[ ! -z "${redis_pid}" ]]; then
+        kill -TERM ${redis_pid}
+        tail --pid=${redis_pid} -f /dev/null > /dev/null 2>&1
+    fi
     exit 1
 fi
 
-pbench-tool-meister-stop
+_PBENCH_TOOL_MEISTER_STOP_LOG_LEVEL="debug" pbench-tool-meister-stop --sysinfo="none" ${group}
 status=${?}
 if [[ ${status} -ne 0 ]]; then
     printf -- "\"pbench-tool-meister-stop\" failed to execute successfully (exit code: ${status})\n" >&2
+    redis_pid="$(cat ${redis_pid_file} 2> /dev/null)"
+    if [[ ! -z "${redis_pid}" ]]; then
+        kill -TERM ${redis_pid}
+        tail --pid=${redis_pid} -f /dev/null > /dev/null 2>&1
+    fi
     exit 1
 fi
